version: '3.8'
services:
  ms-orders-api:
    build: .
    ports:
      - "4000:4000"
    depends_on:
      - db-orders
      - ms-clientes-api
      - ms-menu-api
    environment:
      - MONGO_URI=mongodb://db-orders:27017/ordersdb
      - CLIENTES_URL=http://ms-clientes-api:3000
      - MENU_URL=http://ms-menu-api:5000

  db-orders:
    image: mongo:6
    ports:
      - "27017:27017"

  ms-clientes-api:
    image: tuimagen/ms-clientes
    ports:
      - "3000:3000"

  ms-menu-api:
    image: tuimagen/ms-menu
    ports:
      - "5000:5000"
